export enum ACTIONS {
    ADD_IMG_INFO,
    UPDATE_EXCHANGE_COIN_INFO,
    UPDATE_TRADE_WS_INFO,
    UPDATE_ORDERBOOK_WS_INFO,
    UPDATE_CURRENCY_INFO,
    UPDATE_DOMINANCE_INFO,
    UPDATE_MARKETCAP_INFO,
}